### ISSUE TITLE
Update Apache Storm

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/linkchecker#1]
Apache Storm used for Stormcrawler is version 1.2 but Apache Strom latest version is >=2.

Note that Stormcrawler v2.0 uses Storm v2.x. (see v1.6 ... v2.0 [comparison](https://github.com/DigitalPebble/storm-crawler/compare/1.16...2.0))

**Comment by wowasa** [comment]
implemented in v. 2.1.0. 
storm is v. 2.2.0 and storm crawler v. 2.1 (since v. 2.2 is still in test state)
