### ISSUE TITLE
externalize crawler-conf.yaml

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/linkchecker#20]
since there are so many parameters in the configuration file to try out, the crawler-conf.yaml should be mapped to the host instead of the use of environment variables

**Comment by twagoo** [comment]
Small additional suggestion to this: provide a default that can be overridden, so that it also works out of the box - at least at the compose level. For an example, see e.g. https://gitlab.com/CLARIN-ERIC/compose_vlo/-/blob/master/clarin/docker-compose.yml#L87

**Comment by wowasa** [comment]
closing this for the moment since even in most cases where we override the crawler's default values, we set the values once for all instances and don't modify them
