### ISSUE TITLE
review log levels in MetricsFetcherBolt

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/linkchecker#23]
The bolt has a lot of logging on info level which was copied-pasted from storm crawler's FetcherBolt. If I'm not wrong, Twan's feature request is to have this logging on debug-level and to have an aggregated logging on info level for every hundred/thousand of processed URLs (requires a static synchronized counter)

**Comment by twagoo** [comment]
My (untested and incomplete) code suggestion:
```java
private AtomicInteger counter = new AtomicInteger();
private long lastCheckpoint = System.currentTimeMillis();

public synchronised void countAndLog() {
 if(counter.incrementAndGet() >= LIMIT) {
  long secondsDiff = System.currentTimeMillis() - lastCheckpoint;
  log.info("Checked %d links in the last %d ms", counter.get(), secondsDiff);
  counter.set(0);
  lastCheckpoint = System.currentTimeMillis();
 }
}
```

This instance needs to be shared by all worker threads.

**Comment by wowasa** [comment]
done for version 2.2
